<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * itemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
