<?php

namespace VanoFashion\EShoppingBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ItemProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemProductRepository extends \Doctrine\ORM\EntityRepository
{


	/**
	 *get products in database
	 */

	public function getProducts($page, $nbPerPage , array $filter=null){

		$qb=$this->createQueryBuilder('p')
		         ->leftJoin('p.gender', 'g')
                 ->addSelect('g');


        if($filter!==null and count($filter)>0){
		      foreach ($filter as $key => $value) {
		        if ($key==="gender") {
		           # code...
		          $qb->andWhere($qb->expr()->in('g.'.$key, $value));
		         }
		         else{
		          $qb->andWhere($qb->expr()->in('i.'.$key, $value));
		         }
		      }
        }               
                 
        $qb->orderBy('p.name', 'ASC')
           ->getQuery();         

         $qb->setFirstResult(($page-1) * $nbPerPage);      

         $qb->setMaxResults($nbPerPage);       

        return new Paginator($qb, true);

        

	}

	

	


}
