<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * ItemProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemProductRepository extends \Doctrine\ORM\EntityRepository
{

	

	


}
