<?php

namespace VanoFashion\EShoppingBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ItemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCategoryRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 *get categories with its products in database
	 */

	public function getCategories($page, $nbPerPage){

		$qb=$this->createQueryBuilder('c')
                 ->leftJoin('c.products', 'p')
                 ->addSelect('p')
                 ->orderBy('c.name', 'ASC')
                 ->getQuery();         

         $qb->setFirstResult(($page-1) * $nbPerPage);      

         $qb->setMaxResults($nbPerPage);       

        return new Paginator($qb, true);

        

	}

        /**
         *get a category with its products in database
         */

        public function getCategory($id){

                $qb=$this->createQueryBuilder('c')
                 ->where('c.id = :id')
                 ->setParameter('id', $id)                  
                 ->leftJoin('c.products', 'p')
                 ->addSelect('p')                                
                 ->getQuery();         

                return $qb->getSingleResult();
        

        }



}
