<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * ItemStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemStockRepository extends \Doctrine\ORM\EntityRepository
{
}
