<?php

namespace VanoFashion\EShoppingBundle\Repository;


use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{

  /**
   * get all items
   */
	public function getItems($page, $nbPerPage, array $filter=null){

		$qb=$this->createQueryBuilder('i')
                 ->innerJoin('i.stocks', 's')
                 ->addSelect('s')
                 ->innerJoin('i.gender', 'g')
                 ->addSelect('g')
                 ->innerJoin('i.product', 'p')
                 ->addSelect('p')
                 ->innerJoin('i.images', 'img')
                 ->addSelect('img');
                 
        
    if($filter!==null or count($filter>0)){
      foreach ($filter as $key => $value) {
        # code...
         if($key==="product"){
          $qb->andWhere($qb->expr()->in('p.name', $value));
         }
         elseif ($key==="gender") {
           # code...
          $qb->andWhere($qb->expr()->in('g.'.$key, $value));
         }
         else{
          $qb->andWhere($qb->expr()->in('i.'.$key, $value));
         }
      }
    }

    $qb->groupBy('i.codeItem')
                 ->orderBy('i.addingDate', 'DESC')
                 ->getQuery();

    $qb->setFirstResult(($page-1) * $nbPerPage);      

    $qb->setMaxResults($nbPerPage);       

    return new Paginator($qb, true);

	}




  /**
   * get item with a given id
   */

  public function getItem($id){

    $qb=$this->createQueryBuilder('i')
            ->where('i.id = :id')
            ->setParameter('id',$id)
            ->innerJoin('i.stocks', 's')
            ->addSelect('s')
            ->innerJoin('i.images', 'img')
            ->addSelect('img');
    
   
    return $qb->getQuery()
              ->getSingleResult();

  }
}
