<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemRepository extends \Doctrine\ORM\EntityRepository
{
}
