<?php

namespace VanoFashion\EShoppingBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ItemProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemProductRepository extends \Doctrine\ORM\EntityRepository
{


	/**
	 *get products in database
	 */

	public function getProducts($page, $nbPerPage){

		$qb=$this->createQueryBuilder('p')
                 //->innerJoin('c.products', 'p')
                 //->addSelect('p')
                 ->orderBy('p.name', 'ASC')
                 ->getQuery();         

         $qb->setFirstResult(($page-1) * $nbPerPage);      

         $qb->setMaxResults($nbPerPage);       

        return new Paginator($qb, true);

        

	}

	

	


}
