<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * ItemMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
