<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * itemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
