<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * itemStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemStockRepository extends \Doctrine\ORM\EntityRepository
{
}
