<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * ItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemGenderRepository extends \Doctrine\ORM\EntityRepository
{
}
