<?php

namespace VanoFashion\EShoppingBundle\Repository;

/**
 * itemProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemProductRepository extends \Doctrine\ORM\EntityRepository
{

	

	


}
