vano_fashion_e_shopping_homepage:
    path:     /{_locale}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:index, _locale: en }
    requirements:
        _locale: en|fr



vano_fashion_e_shopping_men_shop:
    path:     /{_locale}/men
    defaults: { _controller: VanoFashionEShoppingBundle:Item:menShop, _locale: en }
    requirements:
        _locale: en|fr




vano_fashion_e_shopping_website_management:
    path: /websitemanagement/{_locale}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:websitemanagement , _locale: en }
    requirements:
        _locale: en|fr


vano_fashion_e_shopping_website_management_item_list:
    path: /websitemanagement/{_locale}/item/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:managementListItemView , _locale: en , page: 1 }
    requirements:
        _locale: en|fr
        page:   \d*

vano_fashion_e_shopping_website_management_item_view:
    path: /websitemanagement/{_locale}/item/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:managementItemView , _locale: en }
    requirements:
        _locale: en|fr
        id:   \d*

vano_fashion_e_shopping_website_management_item_edit:
    path: /websitemanagement/{_locale}/item/edit/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemEdit , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_item_delete:
    path: /websitemanagement/item/delete/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemDelete }


vano_fashion_e_shopping_website_management_item_add:
    path: /websitemanagement/{_locale}/item/add
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemAdd , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_itemcategory_list:
    path: /websitemanagement/{_locale}/itemCategory/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:managementListCategoryView , _locale: en , page: 1 }
    requirements:
        _locale: en|fr
        page:   \d*


vano_fashion_e_shopping_website_management_itemcategory_edit:
    path: /websitemanagement/{_locale}/itemCategory/edit/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemCategoryEdit , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_itemcategory_delete:
    path: /websitemanagement/itemCategory/delete/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemCategoryDelete  }


vano_fashion_e_shopping_website_management_itemcategory_add:
    path: /websitemanagement/{_locale}/itemCategory/add
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemCategoryAdd , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_itemcategory_get:
    path: /websitemanagement/itemCategory/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:getItemCategory}



vano_fashion_e_shopping_website_management_itemproduct_list:
    path: /websitemanagement/{_locale}/itemProduct/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:managementListProductView , _locale: en , page: 1 }
    requirements:
        _locale: en|fr
        page:   \d*


vano_fashion_e_shopping_website_management_itemproduct_edit:
    path: /websitemanagement/{_locale}/itemProduct/edit/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemProductEdit , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_itemproduct_delete:
    path: /websitemanagement/itemProduct/delete/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemProductDelete }


vano_fashion_e_shopping_website_management_itemproduct_add:
    path: /websitemanagement/{_locale}/itemProduct/add
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemProductAdd , _locale: en }
    requirements:
        _locale: en|fr
vano_fashion_e_shopping_website_management_itemproduct_get:
    path: /websitemanagement/itemProduct/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:getItemProduct }


vano_fashion_e_shopping_website_management_itemgender_list:
    path: /websitemanagement/{_locale}/itemGender/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:managementListGenderView , _locale: en , page: 1 }
    requirements:
        _locale: en|fr
        page:   \d*


vano_fashion_e_shopping_website_management_itemgender_edit:
    path: /websitemanagement/{_locale}/itemGender/edit/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemGenderEdit , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_itemgender_delete:
    path: /websitemanagement/itemGender/delete/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemGenderDelete }


vano_fashion_e_shopping_website_management_itemgender_add:
    path: /websitemanagement/{_locale}/itemGender/add
    defaults: { _controller: VanoFashionEShoppingBundle:Item:itemGenderAdd , _locale: en }
    requirements:
        _locale: en|fr




