vano_fashion_e_shopping_homepage:
    path:     /{_locale}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:index, _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_view_customerType:
    path: /{customerType}/{catalogType}/{_locale}/list/{page}
    defaults:
        _controller: VanoFashionEShoppingBundle:Item:viewCustomerType 
        _locale: en 
        page: 1 
        catalogType: catalog    
    requirements:
        _locale: en|fr
        page:   \d*
        catalogType: sale|catalog

vano_fashion_e_shopping_view_itemProduct:
    path: /{customerType}/{catalogType}/{product}/{_locale}/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:viewProduct , _locale: en , page: 1 , catalogType:catalog}
    requirements:
        _locale: en|fr
        page:   \d*
        catalogType: sale|catalog



vano_fashion_e_shopping_view_itemCategory:
    path: /{customerType}/{catalogType}/{product}/{category}/{_locale}/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:viewCategory , _locale: en , page: 1 , catalogType:catalog}
    requirements:
        _locale: en|fr
        page:   \d*
        catalogType: sale|catalog

vano_fashion_e_shopping_view_item:
    path: /item/{id}/{_locale}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:view , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_item_list:
    path: /website management/{_locale}/item/list/{page}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:managementListItemView , _locale: en , page: 1 }
    requirements:
        _locale: en|fr
        page:   \d*


vano_fashion_e_shopping_website_management_item_add:
    path: /website management/{_locale}/item/add
    defaults: { _controller: VanoFashionEShoppingBundle:Item:add , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_item_edit:
    path: /website management/{_locale}/item/edit/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:add , _locale: en }
    requirements:
        _locale: en|fr

vano_fashion_e_shopping_website_management_item_delete:
    path: /website management/{_locale}/item/delete/{id}
    defaults: { _controller: VanoFashionEShoppingBundle:Item:delete , _locale: en }
    requirements:
        _locale: en|fr




